language: cpp

sudo: required
dist: trusty
osx_image: xcode7.3
cache: ccache

# Travis CI VM OSs
os:
    - linux
    - osx

# Travis CI build matrix components
compiler:
    - gcc
    - clang

env:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release

before_install:
    # Update package managers
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-get -qq update;  fi
    - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update;         fi
    
    # Use ccache also for clang and clang++ on linux
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CC" == "clang" ];    then sudo ln -s ../../bin/ccache /usr/lib/ccache/clang;   fi; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CC" == "clang" ];    then export CFLAGS="-Qunused-arguments";                  fi; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "clang++" ]; then sudo ln -s ../../bin/ccache /usr/lib/ccache/clang++; fi; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-Qunused-arguments";                fi; fi

    # Install ccache on osx
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ccache;                               fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

    # Print some more system information after installing all build tools
    - echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
    - uname -a
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then lsb_release -a;                     fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];   then system_profiler SPSoftwareDataType; fi
    - env
    - which cmake
    - cmake --version
    - which $CC
    - $CC --version
    - which $CXX
    - $CXX --version
    - which ccache
    - ccache --version
    - ccache -s
    - echo "--------------------  END SYSTEM INFORMATION  --------------------"

before_script:
    # Run CMake
    - mkdir build
    - cd build
    - cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..

script:
    - make
    - make test
